# Generated by Django 4.2.2 on 2023-06-30 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_posts_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
