# Generated by Django 4.2.2 on 2023-07-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0008_alter_comment_options_comment_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='posts',
            name='topic',
            field=models.CharField(choices=[('', 'Wybierz temat'), ('sold', 'Sprzedam'), ('buy', 'Kupię'), ('rent', 'Wypożyczę'), ('look', 'Szukam'), ('else', 'Inne')], default='', max_length=4),
        ),
    ]
