# Generated by Django 4.2.2 on 2023-07-03 14:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Registration', '0010_posts_recommends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='recommends',
            field=models.ManyToManyField(blank=True, related_name='recommends', to=settings.AUTH_USER_MODEL),
        ),
    ]
